# Generated by Django 6.1.1 on 2026-09-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='новая', max_length=50),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
